name: DOE Pipeline SA

 

on:
  push:
    branches:
      - main

 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

 

      - name: Install dependencies
        run: npm install

 

      - name: Build
        run: npm run build

 

      - name: Test
        run: npm run test

 

      - name: Deploy to Staging
        run: npm run deploy

 

  notify-failure:
    needs: build-test-deploy
    runs-on: ubuntu-latest

 

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yagmail

 

      - name: Send email notification on failure
        run: |
          import yagmail
          yag = yagmail.SMTP(
            user='${{ secrets.GMAIL_USERNAME }}',
            password='${{ secrets.GMAIL_PASSWORD }}',
            host='smtp.gmail.com',
            port=587,
          )
          subject = "CI/CD Pipeline Failed"
          contents = "The CI/CD pipeline has failed. Please check the logs for details."
          yag.send('${{ secrets.GMAIL_USERNAME }}', subject, contents)
        if: ${{ failure() }}
